# Generated by Django 3.2.7 on 2021-12-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211215_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review',
            field=models.TextField(default='No Review Provided'),
            preserve_default=False,
        ),
    ]
